#!/usr/bin/env bash

# gem install video_info
# gem install hpricot


# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

# ERROR: read server certificate B: certificate verify failed
# SOLUTION =>
# brew update && brew upgrade openssl
# rvm osx-ssl-certs update all
# rvm reinstall ruby-2.2.3 --with-openssl-dir=/usr/local

JSON_FILE="links"

function run(){
	# for each attributes
	jq -r '.[]' $JSON_FILE |\
	while read href
	do
	  	echo "href: [$href]"
	    
	    # get data of each attribute

		youtube-dl "$href"

	  	echo "------------------------------"

	done
}

run
